config/routes.rb
Colchonet::Application.routes.draw do
  get "bookings/index"
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  root :to => 'bookings#index'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  resources :users
  resources :rooms do
     resources :bookings, only: [:new, :create, :update], module: :rooms
  end
  resources :bookings, only: [:index, :show]
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room 
  validates_presence_of :start_at, :end_at, :room_id

  validate :cannot_start_or_end_at_reserved_date, :cannot_end_at_be_less_than_or_equal_to_start_at, :if => lambda{ |object| object.start_at.present? and object.end_at.present? }
  validate :cannot_start_at_past, :if => lambda{ |object| object.start_at.present? }
  validate :cannot_end_at_past, :if => lambda{ |object| object.end_at.present?}



  def cannot_start_or_end_at_reserved_date
    errors.add(:start_at, :exclusion) if room.reserved_in?(start_at.to_date)
    errors.add(:end_at, :exclusion) if room.reserved_in?(end_at.to_date) 
  end

  def cannot_end_at_be_less_than_or_equal_to_start_at
    errors.add(:end_at, :invalid) unless end_at.after? start_at
  end
  
  def cannot_start_at_past
    errors.add(:start_at, :exclusion) if self.start_at.to_date.is_past?
  end

  def cannot_end_at_past
    errors.add(:end_at, :exclusion) if self.end_at.to_date.is_past?
  end

  has_event_calendar

end

app/models/room.rb
class Room < ActiveRecord::Base
   validates_presence_of :number, :description
   validates_uniqueness_of :number

   has_many :bookings do
     def persisted
        collect { |booking| booking if booking.persisted? }
     end     
   end

   def reserved_in?(date)
      return bookings.exists?(['start_at<=? and end_at>=?', date, date])
   end

end

app/models/user.rb
class User < ActiveRecord::Base
   validates_presence_of :email, :full_name, :password
   validates_uniqueness_of :email

   has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Booking.event_strips_for_month(@shown_month)
  end
  
  def new
     @booking = Booking.new
  end

  def create
     @booking = Booking.new(booking_params)
     if @booking.save
        redirect_to @booking, :notice => 'Reserva efetuada com sucesso!'
     else
        render :new
     end
  end

  def show
     @booking = Booking.find(params[:id])
  end

  private

  def booking_params
     params.require(:booking).permit(:start_at, :end_at)
  end 
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month)
  end
  
end

app/controllers/rooms/bookings_controller.rb
class Rooms::BookingsController < ApplicationController
   def new
       @booking = room.bookings.build
   end

   def create
      @booking = room.bookings.build booking_params
      if @booking.save
          redirect_to bookings_path, :notice => 'Reserva efetuada com sucesso!'
      else
          render :new
      end
   end

   private
   def room
      @room ||= Room.find(params[:room_id])
   end

   def booking_params
       params.require(:booking).permit(:start_at, :end_at	)
   end
   

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
   def index
     @rooms = Room.all
   end

   def new
      @room = Room.new
   end
  
   def create
      @room = Room.new(room_params)
      if @room.save
         redirect_to @room, :notice => 'Quarto criado com sucesso!'
      else
         render :new
      end
   end
  
   def show
      @room = Room.find(params[:id])   
   end

   private
   
   def room_params
      params.require(:room).permit(:number, :description)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
     @user = User.new
   end
   
   def create 
     @user = User.new(user_params)
     if @user.save
        redirect_to @user, :notice => "Usuário cadastrado com sucesso!"
     else
        render :new
     end
   end
  
   def show
      @user = User.find(params[:id])
   end
  
   def edit
     @user = User.find(params[:id])
   end
   
   def update
     @user = User.find(params[:id])
     if @user.update(user_params)
        redirect_to @user, :notice => "Usuário editado com sucesso!"
     else
        render :new
     end
   end
    

   private

   def user_params
      params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      booking = args[:event]
      %(<a href="/bookings/#{booking.id}" title="Quarto ##{booking.room.number}">Quarto ##{booking.room.number}</a>)
    end
  end
end

app/views/bookings/_form.html.erb
<%= form_for [:room,@booking] do |f| %>
  <p>
    <%= f.label :start_at %>
    <%= date_select :booking, :start_at, :id => 'booking_start_at', selected: Date.today, :class => 'form-control' %>
  </p>
  <p>
  <%= f.label :end_at %>
  <%= date_select :booking, :end_at, :id => 'booking_end_at', selected: Date.tomorrow, :class => 'form-control' %>
  </p>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<%= raw(event_calendar) %>

app/views/bookings/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

app/views/bookings/show.html.erb
<h1>Quarto #<%= @booking.id %></h1>
<p>Entra: <%= l(@booking.start_at, format: :long) %></p>
<p>Termina: <%= l(@booking.end_at, format: :long) %></p>

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1>Calendar</h1>

<%= raw(event_calendar) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
   <%= f.label :number %>
   <%= f.text_field :number %>
   <%= f.label :description %>
   <%= f.text_field :description %>
   <%= f.submit %>
<% end %>

app/views/rooms/bookings/_form.html.erb
<%= form_for [:room,@booking] do |f| %>
  <p>
    <%= f.label :start_at %>
    <%= date_select :booking, :start_at, :id => 'booking_start_at', selected: Date.today, :class => 'form-control' %>
  </p>
  <p>
  <%= f.label :end_at %>
  <%= date_select :booking, :end_at, :id => 'booking_end_at', selected: Date.tomorrow, :class => 'form-control' %>
  </p>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/rooms/bookings/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

app/views/rooms/index.html.erb
<table class="table table-stripped">
   <tr>
     <th>#</th>
     <th><%= t('activerecord.attributes.room.description') %></th>
     <th></th>
   </tr>
<% @rooms.each do |room| %>
  <tr>
    <td>Quarto # <%= room.id %></td>
    <td><%= room.description %></td>
    <td><%= link_to 'Ver detalhes do quarto', room %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Criar novo quarto', new_room_path, :class => 'btn btn-primary' %>

app/views/rooms/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

app/views/rooms/show.html.erb
<%= @room.id %>
<%= @room.description %>

<%= link_to 'Fazer reserva', new_room_booking_path(@room) %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
   <div id="erros_explanations">
     <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
     <% end %>
   </div>
<% end %>

<%= form_for @user do |f| %>
   <p>
     <%= f.label :email %>
     <%= f.text_field :email %>
   </p>
   <p>
     <%= f.label :password %>
     <%= f.password_field :password %>
   </p>
   <p>
     <%= f.label :password_confirmation %>
     <%= f.password_field :password_confirmation %>
   <p>
     <%= f.label :full_name %>
     <%= f.text_field :full_name %>
   </p>
   <p>
     <%= f.submit %>
   </p>
<% end %>

app/views/users/edit.html.erb
<h1>Editar</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Cadastro</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<p>Email: <%= @user.email %></p>

<%= link_to "Editar usuário", edit_user_path(@user) %>